// 📄 Path: scratch/generateExerciseData.js
const fs = require('fs');
const path = require('path');

const targetDir = path.join(__dirname, '../data/exercises');
if (!fs.existsSync(targetDir)) {
    fs.mkdirSync(targetDir, { recursive: true });
}

// 1. CHEST
const chestExercises = [
    {
        id: "barbell-bench-press",
        name: "Barbell Bench Press",
        category: "main",
        primaryMuscle: "Chest",
        secondaryMuscles: ["Triceps", "Front Delts"],
        targetMuscles: "Chest, Triceps, Anterior Deltoids",
        movementType: "push",
        equipment: ["barbell", "bench"],
        locations: ["gym"],
        difficulty: "intermediate",
        goalTags: ["strength", "muscle_gain"],
        contraindications: ["shoulder", "wrist"],
        defaultSets: 4,
        defaultReps: { min: 6, max: 10 },
        defaultRepRange: { min: 6, max: 10 },
        restSec: 90,
        isTimed: false,
        durationSec: 0,
        intensity: "high",
        caloriesPerMinute: 7.5,
        instructions: [
            "Lie flat on the bench with eyes directly under the bar.",
            "Grip the bar slightly wider than shoulder-width, plant feet firmly.",
            "Unrack and lower with control to the mid-chest.",
            "Press powerfully upward without locking out elbows aggressively."
        ],
        commonMistakes: ["Flaring elbows at 90 degrees", "Bouncing bar off the sternum"],
        coachTips: ["Retract shoulder blades and maintain a slight natural arch in the lower back.", "Drive through your heels for stability."],
        breathingTip: "Inhale on the descent; exhale forcefully on the press.",
        safeAlternativeIds: ["dumbbell-floor-press", "incline-push-up"],
        progressionNote: "Add 2.5kg when you complete 4x10 reps with solid form.",
        imageUrl: null,
        gifUrl: null,
        videoUrl: null
    },
    {
        id: "dumbbell-bench-press",
        name: "Dumbbell Bench Press",
        category: "main",
        primaryMuscle: "Chest",
        secondaryMuscles: ["Triceps", "Front Delts"],
        targetMuscles: "Chest, Triceps, Stabilizers",
        movementType: "push",
        equipment: ["dumbbell", "bench"],
        locations: ["gym", "home"],
        difficulty: "intermediate",
        goalTags: ["muscle_gain", "strength"],
        contraindications: ["shoulder"],
        defaultSets: 3,
        defaultReps: { min: 8, max: 12 },
        defaultRepRange: { min: 8, max: 12 },
        restSec: 75,
        isTimed: false,
        durationSec: 0,
        intensity: "medium",
        caloriesPerMinute: 6.5,
        instructions: [
            "Sit on the edge of a flat bench holding dumbbells on knees.",
            "Kick back and bring the weights to the outside of your chest.",
            "Press dumbbells up in a slight arc until arms are extended.",
            "Lower slowly until elbows reach bench height."
        ],
        commonMistakes: ["Clinking dumbbells at the top", "Dropping weights abruptly"],
        coachTips: ["Allows a deeper stretch than barbells and balances side-to-side asymmetries."],
        breathingTip: "Breathe in deeply as dumbbells lower; exhale as you push up.",
        safeAlternativeIds: ["dumbbell-floor-press", "standard-push-up"],
        progressionNote: "Progress by 1-2 kg per dumbbell when hitting the top rep range.",
        imageUrl: null,
        gifUrl: null,
        videoUrl: null
    },
    {
        id: "incline-dumbbell-press",
        name: "Incline Dumbbell Press",
        category: "main",
        primaryMuscle: "Chest",
        secondaryMuscles: ["Upper Chest", "Front Delts", "Triceps"],
        targetMuscles: "Clavicular Head (Upper Chest), Shoulders",
        movementType: "push",
        equipment: ["dumbbell", "bench"],
        locations: ["gym", "home"],
        difficulty: "intermediate",
        goalTags: ["muscle_gain", "strength"],
        contraindications: ["shoulder"],
        defaultSets: 3,
        defaultReps: { min: 8, max: 12 },
        defaultRepRange: { min: 8, max: 12 },
        restSec: 75,
        isTimed: false,
        durationSec: 0,
        intensity: "medium",
        caloriesPerMinute: 6.8,
        instructions: [
            "Set bench to a 30 to 45 degree angle.",
            "Lie back and press dumbbells above upper chest.",
            "Lower slowly until you feel a comfortable stretch in the upper pectorals.",
            "Press back up smoothly."
        ],
        commonMistakes: ["Setting the incline too steep (turns into shoulder press)"],
        coachTips: ["30 degrees is optimal to hit upper chest without straining the anterior delt."],
        breathingTip: "Inhale on the way down; exhale as you press up.",
        safeAlternativeIds: ["incline-push-up"],
        progressionNote: "Aim for clean controlled 3-second negatives before raising load.",
        imageUrl: null,
        gifUrl: null,
        videoUrl: null
    },
    {
        id: "standard-push-up",
        name: "Standard Push-Up",
        category: "main",
        primaryMuscle: "Chest",
        secondaryMuscles: ["Triceps", "Anterior Deltoids", "Core"],
        targetMuscles: "Chest, Triceps, Core",
        movementType: "push",
        equipment: ["bodyweight", "none"],
        locations: ["home", "gym"],
        difficulty: "beginner",
        goalTags: ["fat_loss", "muscle_gain", "endurance"],
        contraindications: ["wrist", "shoulder"],
        defaultSets: 3,
        defaultReps: { min: 10, max: 15 },
        defaultRepRange: { min: 10, max: 15 },
        restSec: 60,
        isTimed: false,
        durationSec: 0,
        intensity: "medium",
        caloriesPerMinute: 6.0,
        instructions: [
            "Start in high plank position with hands slightly wider than shoulder-width.",
            "Lower chest towards floor by bending elbows back at 45 degrees.",
            "Push floor away firmly to return to starting position."
        ],
        commonMistakes: ["Sagging hips", "Elbows flaring 90 degrees out"],
        coachTips: ["Squeeze glutes and brace your core throughout every rep."],
        breathingTip: "Inhale going down; exhale pushing up.",
        safeAlternativeIds: ["incline-push-up"],
        progressionNote: "Elevate feet to progress towards decline push-ups.",
        imageUrl: null,
        gifUrl: null,
        videoUrl: null
    },
    {
        id: "incline-push-up",
        name: "Incline Push-Up (Joint-Friendly)",
        category: "main",
        primaryMuscle: "Chest",
        secondaryMuscles: ["Triceps", "Core"],
        targetMuscles: "Lower Chest, Triceps",
        movementType: "push",
        equipment: ["bench", "bodyweight"],
        locations: ["home", "gym"],
        difficulty: "beginner",
        goalTags: ["fat_loss", "general_fitness"],
        contraindications: [], // Safe alternative for wrist and shoulder
        defaultSets: 3,
        defaultReps: { min: 12, max: 15 },
        defaultRepRange: { min: 12, max: 15 },
        restSec: 45,
        isTimed: false,
        durationSec: 0,
        intensity: "low",
        caloriesPerMinute: 4.8,
        instructions: [
            "Place hands shoulder-width apart on a sturdy bench or raised platform.",
            "Keep spine aligned as you lower your chest to the bench edge.",
            "Push away to full arm extension."
        ],
        commonMistakes: ["Bending at the hips"],
        coachTips: ["Excellent alternative if you have wrist stiffness or shoulder impingement."],
        breathingTip: "Smooth breathing in sync with repetitions.",
        safeAlternativeIds: ["standard-push-up"],
        progressionNote: "Lower the platform height progressively to reach the floor.",
        imageUrl: null,
        gifUrl: null,
        videoUrl: null
    },
    {
        id: "dumbbell-floor-press",
        name: "Dumbbell Floor Press (Shoulder Safe)",
        category: "main",
        primaryMuscle: "Chest",
        secondaryMuscles: ["Triceps"],
        targetMuscles: "Pectorals, Triceps Brachii",
        movementType: "push",
        equipment: ["dumbbell"],
        locations: ["home", "gym"],
        difficulty: "beginner",
        goalTags: ["muscle_gain", "strength"],
        contraindications: [], // Extremely safe for shoulders
        defaultSets: 3,
        defaultReps: { min: 10, max: 12 },
        defaultRepRange: { min: 10, max: 12 },
        restSec: 60,
        isTimed: false,
        durationSec: 0,
        intensity: "medium",
        caloriesPerMinute: 5.5,
        instructions: [
            "Lie flat on the floor with knees bent and feet flat.",
            "Hold dumbbells with triceps resting on the floor.",
            "Press weights up until arms are extended over chest.",
            "Lower slowly until upper arms lightly touch the floor, pause briefly, repeat."
        ],
        commonMistakes: ["Slamming elbows into the floor"],
        coachTips: ["The floor limits shoulder extension, protecting the anterior capsule."],
        breathingTip: "Inhale down, exhale up.",
        safeAlternativeIds: ["standard-push-up"],
        progressionNote: "Increase weight once you can complete 12 clean reps with 1s pause.",
        imageUrl: null,
        gifUrl: null,
        videoUrl: null
    },
    {
        id: "cable-chest-flye",
        name: "Cable Chest Flye",
        category: "main",
        primaryMuscle: "Chest",
        secondaryMuscles: ["Anterior Deltoids"],
        targetMuscles: "Sternal Head of Pectoralis Major",
        movementType: "push",
        equipment: ["cable_machine"],
        locations: ["gym"],
        difficulty: "intermediate",
        goalTags: ["muscle_gain"],
        contraindications: ["shoulder"],
        defaultSets: 3,
        defaultReps: { min: 12, max: 15 },
        defaultRepRange: { min: 12, max: 15 },
        restSec: 60,
        isTimed: false,
        durationSec: 0,
        intensity: "medium",
        caloriesPerMinute: 5.2,
        instructions: [
            "Set cables at chest height, grab handles and step forward in a split stance.",
            "With slightly bent elbows, bring handles together in a hugging motion.",
            "Squeeze chest for 1 second, then control back to a stretch."
        ],
        commonMistakes: ["Bending elbows too much turning it into a press"],
        coachTips: ["Imagine hugging a large barrel to keep arm angle locked."],
        breathingTip: "Exhale on contraction; inhale on stretch.",
        safeAlternativeIds: ["dumbbell-floor-press"],
        progressionNote: "Focus on mind-muscle squeeze rather than maximum pin weight.",
        imageUrl: null,
        gifUrl: null,
        videoUrl: null
    },
    {
        id: "chest-dips",
        name: "Chest Dips",
        category: "main",
        primaryMuscle: "Chest",
        secondaryMuscles: ["Triceps", "Front Delts"],
        targetMuscles: "Lower Pectorals, Triceps",
        movementType: "push",
        equipment: ["bodyweight", "bench"],
        locations: ["gym"],
        difficulty: "advanced",
        goalTags: ["muscle_gain", "strength"],
        contraindications: ["shoulder", "wrist"],
        defaultSets: 3,
        defaultReps: { min: 8, max: 12 },
        defaultRepRange: { min: 8, max: 12 },
        restSec: 90,
        isTimed: false,
        durationSec: 0,
        intensity: "high",
        caloriesPerMinute: 8.0,
        instructions: [
            "Mount parallel bars and lean your torso slightly forward (30 degrees).",
            "Lower body by bending elbows until upper arms are parallel to the ground.",
            "Push back up focusing on chest activation."
        ],
        commonMistakes: ["Staying upright (targets triceps more than chest)", "Going too deep into shoulder impingement"],
        coachTips: ["Keep chin tucked and cross ankles for balance."],
        breathingTip: "Inhale descending; exhale pushing up.",
        safeAlternativeIds: ["incline-push-up", "dumbbell-bench-press"],
        progressionNote: "Add a dip belt with 2.5-5kg when bodyweight reaches 3x12.",
        imageUrl: null,
        gifUrl: null,
        videoUrl: null
    }
];

// 2. BACK
const backExercises = [
    {
        id: "pull-up",
        name: "Pull-Up",
        category: "main",
        primaryMuscle: "Back",
        secondaryMuscles: ["Lats", "Biceps", "Upper Back"],
        targetMuscles: "Latissimus Dorsi, Biceps, Rhomboids",
        movementType: "pull",
        equipment: ["pull_up_bar", "bodyweight"],
        locations: ["gym", "home"],
        difficulty: "advanced",
        goalTags: ["strength", "muscle_gain"],
        contraindications: ["shoulder", "elbow"],
        defaultSets: 3,
        defaultReps: { min: 5, max: 8 },
        defaultRepRange: { min: 5, max: 8 },
        restSec: 90,
        isTimed: false,
        durationSec: 0,
        intensity: "high",
        caloriesPerMinute: 8.5,
        instructions: [
            "Grip the pull-up bar overhand slightly wider than shoulder width.",
            "Pull chest toward the bar by driving elbows down and back.",
            "Clear bar with chin, pause, and lower under complete control."
        ],
        commonMistakes: ["Kipping or swinging legs", "Half reps without full extension"],
        coachTips: ["Depress shoulder blades before pulling (active hang to pull)."],
        breathingTip: "Exhale as you pull up; inhale as you lower.",
        safeAlternativeIds: ["lat-pulldown", "inverted-row"],
        progressionNote: "Use resistance band assistance if needed; advance to weighted pull-ups.",
        imageUrl: null,
        gifUrl: null,
        videoUrl: null
    },
    {
        id: "lat-pulldown",
        name: "Lat Pulldown",
        category: "main",
        primaryMuscle: "Back",
        secondaryMuscles: ["Biceps", "Upper Back"],
        targetMuscles: "Latissimus Dorsi",
        movementType: "pull",
        equipment: ["cable_machine"],
        locations: ["gym"],
        difficulty: "beginner",
        goalTags: ["muscle_gain", "strength"],
        contraindications: ["shoulder"],
        defaultSets: 3,
        defaultReps: { min: 10, max: 12 },
        defaultRepRange: { min: 10, max: 12 },
        restSec: 60,
        isTimed: false,
        durationSec: 0,
        intensity: "medium",
        caloriesPerMinute: 6.2,
        instructions: [
            "Sit securely with thighs tucked under the pads.",
            "Grip bar wide, lean back slightly (10-15 degrees).",
            "Pull bar down smoothly to upper collarbone.",
            "Return bar with controlled stretch to starting position."
        ],
        commonMistakes: ["Leaning back too far turning it into a row", "Pulling behind the neck"],
        coachTips: ["Lead the movement with your elbows, pulling them down towards your pockets."],
        breathingTip: "Exhale as bar reaches chest; inhale as it returns.",
        safeAlternativeIds: ["inverted-row", "seated-cable-row"],
        progressionNote: "Increase pin weight in small 2.5kg increments.",
        imageUrl: null,
        gifUrl: null,
        videoUrl: null
    },
    {
        id: "barbell-bent-over-row",
        name: "Barbell Bent-Over Row",
        category: "main",
        primaryMuscle: "Back",
        secondaryMuscles: ["Lats", "Rhomboids", "Biceps", "Spinal Erectors"],
        targetMuscles: "Mid & Upper Back, Lats",
        movementType: "pull",
        equipment: ["barbell"],
        locations: ["gym"],
        difficulty: "intermediate",
        goalTags: ["strength", "muscle_gain"],
        contraindications: ["lower_back"],
        defaultSets: 4,
        defaultReps: { min: 8, max: 10 },
        defaultRepRange: { min: 8, max: 10 },
        restSec: 90,
        isTimed: false,
        durationSec: 0,
        intensity: "high",
        caloriesPerMinute: 7.8,
        instructions: [
            "Hinge forward at hips with soft knees until torso is at a 45-degree angle.",
            "Hold barbell with an overhand grip just outside knees.",
            "Pull bar into lower ribcage/navel, squeezing shoulder blades together.",
            "Lower barbell under control without rounding back."
        ],
        commonMistakes: ["Rounding lumbar spine", "Jerking torso upright during pull"],
        coachTips: ["Keep core tightly braced and imagine pulling with elbows."],
        breathingTip: "Inhale at the bottom, exhale as you row into your abdomen.",
        safeAlternativeIds: ["chest-supported-t-bar-row", "one-arm-dumbbell-row"],
        progressionNote: "Master hip hinge mechanics before heavy loading.",
        imageUrl: null,
        gifUrl: null,
        videoUrl: null
    },
    {
        id: "chest-supported-t-bar-row",
        name: "Chest-Supported Row (Lower-Back Friendly)",
        category: "main",
        primaryMuscle: "Back",
        secondaryMuscles: ["Rhomboids", "Rear Delts", "Biceps"],
        targetMuscles: "Upper & Mid Back, Trapezius",
        movementType: "pull",
        equipment: ["dumbbell", "bench"],
        locations: ["gym", "home"],
        difficulty: "beginner",
        goalTags: ["muscle_gain", "strength"],
        contraindications: [], // Lower back friendly!
        defaultSets: 3,
        defaultReps: { min: 10, max: 12 },
        defaultRepRange: { min: 10, max: 12 },
        restSec: 60,
        isTimed: false,
        durationSec: 0,
        intensity: "medium",
        caloriesPerMinute: 6.0,
        instructions: [
            "Lie face down on a 45-degree incline bench with dumbbells hanging down.",
            "Row dumbbells upward towards your hips while keeping chest firmly against pad.",
            "Squeeze shoulder blades for 1 second at the top, then lower slowly."
        ],
        commonMistakes: ["Lifting chest off the pad to cheat"],
        coachTips: ["Takes 100% of the strain off your lumbar spine while isolating upper back."],
        breathingTip: "Exhale as you pull; inhale as you release.",
        safeAlternativeIds: ["seated-cable-row"],
        progressionNote: "Focus on peak contraction hold at top.",
        imageUrl: null,
        gifUrl: null,
        videoUrl: null
    },
    {
        id: "one-arm-dumbbell-row",
        name: "One-Arm Dumbbell Row",
        category: "main",
        primaryMuscle: "Back",
        secondaryMuscles: ["Lats", "Biceps", "Forearms"],
        targetMuscles: "Unilateral Lat & Rhomboid",
        movementType: "pull",
        equipment: ["dumbbell", "bench"],
        locations: ["gym", "home"],
        difficulty: "beginner",
        goalTags: ["muscle_gain", "strength"],
        contraindications: [],
        defaultSets: 3,
        defaultReps: { min: 10, max: 12 },
        defaultRepRange: { min: 10, max: 12 },
        restSec: 60,
        isTimed: false,
        durationSec: 0,
        intensity: "medium",
        caloriesPerMinute: 6.5,
        instructions: [
            "Place knee and hand of one side on bench for support, other foot flat on ground.",
            "Hold dumbbell with free hand hanging straight down.",
            "Pull dumbbell upward towards hip crease, keeping elbow tight to ribcage.",
            "Lower slowly to a full lats stretch."
        ],
        commonMistakes: ["Twisting torso excessively to yank the weight"],
        coachTips: ["Pull back towards your pocket, not straight up to your armpit."],
        breathingTip: "Exhale on pull; inhale on stretch.",
        safeAlternativeIds: ["chest-supported-t-bar-row"],
        progressionNote: "Progress independently on each arm to fix imbalances.",
        imageUrl: null,
        gifUrl: null,
        videoUrl: null
    },
    {
        id: "seated-cable-row",
        name: "Seated Cable Row",
        category: "main",
        primaryMuscle: "Back",
        secondaryMuscles: ["Rhomboids", "Lats", "Biceps"],
        targetMuscles: "Mid Back & Latissimus Dorsi",
        movementType: "pull",
        equipment: ["cable_machine"],
        locations: ["gym"],
        difficulty: "beginner",
        goalTags: ["muscle_gain", "strength"],
        contraindications: ["lower_back"],
        defaultSets: 3,
        defaultReps: { min: 10, max: 12 },
        defaultRepRange: { min: 10, max: 12 },
        restSec: 60,
        isTimed: false,
        durationSec: 0,
        intensity: "medium",
        caloriesPerMinute: 6.0,
        instructions: [
            "Sit on the machine with feet against footrests, knees slightly bent.",
            "Grab V-bar attachment with arms extended and upright posture.",
            "Pull handle into lower abdomen while keeping shoulders back and down.",
            "Slowly return to start with control."
        ],
        commonMistakes: ["Rocking aggressively back and forth"],
        coachTips: ["Maintain an upright chest and squeeze your back muscles like pinching a pencil."],
        breathingTip: "Exhale pulling in; inhale returning.",
        safeAlternativeIds: ["chest-supported-t-bar-row", "one-arm-dumbbell-row"],
        progressionNote: "Increase hold duration at full contraction.",
        imageUrl: null,
        gifUrl: null,
        videoUrl: null
    },
    {
        id: "inverted-row",
        name: "Inverted Row (Bodyweight Australian Pull-Up)",
        category: "main",
        primaryMuscle: "Back",
        secondaryMuscles: ["Biceps", "Rear Delts", "Core"],
        targetMuscles: "Upper Back, Scapular Retractors",
        movementType: "pull",
        equipment: ["bodyweight", "barbell"],
        locations: ["home", "gym"],
        difficulty: "beginner",
        goalTags: ["muscle_gain", "general_fitness"],
        contraindications: [],
        defaultSets: 3,
        defaultReps: { min: 8, max: 12 },
        defaultRepRange: { min: 8, max: 12 },
        restSec: 60,
        isTimed: false,
        durationSec: 0,
        intensity: "medium",
        caloriesPerMinute: 5.8,
        instructions: [
            "Position a bar at waist height in a rack or use sturdy table.",
            "Hang underneath with heels on floor and body straight.",
            "Pull chest up to touch the bar.",
            "Lower back down with control."
        ],
        commonMistakes: ["Sagging hips during the movement"],
        coachTips: ["Bend knees to make it easier; elevate feet to make it harder."],
        breathingTip: "Exhale pulling up; inhale lowering down.",
        safeAlternativeIds: ["lat-pulldown"],
        progressionNote: "Step feet forward towards horizontal to increase difficulty.",
        imageUrl: null,
        gifUrl: null,
        videoUrl: null
    },
    {
        id: "face-pull",
        name: "Cable Face Pull",
        category: "main",
        primaryMuscle: "Back",
        secondaryMuscles: ["Rear Delts", "Rotator Cuff", "Upper Traps"],
        targetMuscles: "Posterior Deltoids & Shoulder Health",
        movementType: "pull",
        equipment: ["cable_machine", "resistance_band"],
        locations: ["gym", "home"],
        difficulty: "beginner",
        goalTags: ["mobility", "muscle_gain"],
        contraindications: [],
        defaultSets: 3,
        defaultReps: { min: 12, max: 15 },
        defaultRepRange: { min: 12, max: 15 },
        restSec: 45,
        isTimed: false,
        durationSec: 0,
        intensity: "low",
        caloriesPerMinute: 4.5,
        instructions: [
            "Attach rope to cable set at eye level.",
            "Grip with thumbs pointing backwards.",
            "Pull rope towards bridge of nose while externally rotating shoulders.",
            "Hold for 1 second, feel rear delts and upper back engage."
        ],
        commonMistakes: ["Using too much weight and leaning backwards"],
        coachTips: ["One of the best exercises for shoulder longevity and posture."],
        breathingTip: "Exhale on pull; inhale on release.",
        safeAlternativeIds: ["bent-over-rear-delt-fly"],
        progressionNote: "Prioritize perfect form and pause over weight.",
        imageUrl: null,
        gifUrl: null,
        videoUrl: null
    }
];

// Write chest and back
fs.writeFileSync(path.join(targetDir, 'chest.json'), JSON.stringify(chestExercises, null, 2), 'utf8');
fs.writeFileSync(path.join(targetDir, 'back.json'), JSON.stringify(backExercises, null, 2), 'utf8');
console.log('✅ Created chest.json and back.json');
